---
fixtures:
  forge_modules:
    acl: "puppetlabs/acl"
    chocolatey: "puppetlabs/chocolatey"
    concat: "puppetlabs/concat"
    cygwin: "mdelaney/cygwin"
    registry: "puppetlabs/registry"
    stdlib: "puppetlabs/stdlib"
